name: Generate and Push data.json

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *' # This schedule will run the workflow every day at midnight UTC

jobs:
  generate-and-push-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Node.js Script and Generate data.json
        run: node getter.js > data.json

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add .
          git commit -m "Generate data.json"
          git push origin master